name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ["20.x"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install system dependencies for sharp
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev

      - name: Install npm dependencies
        run: |
          npm ci
          npm install sharp
          npm audit fix --force || true

      - name: Start application with logging
        run: |
          npm install pm2 -g
          pm2 start queen.js --name "Queen_Anju" --watch
          sleep 10
          pm2 logs --lines 50
          curl -f http://localhost:3000 || (pm2 logs && exit 1)
