name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Clean install
        run: |
          rm -rf node_modules
          npm install --package-lock
          npm cache clean --force

      - name: Verify installation
        run: npm list --depth=0 || true

      - name: Start application
        run: npm start
